---
title: Commiting to Good Git Practices
author: Karl Hailperin
date: '2019-10-07'
slug: []
categories: []
tags:
  - git
description: ''
---
One of the skills I have kept struggling the most to cultivate as a data analyst 
is version control. Thanks to the contributions of community members like 
[Jenny Bryan](https://happygitwithr.com/), I know how to commit, branch, merge, 
and submit pull requests and why these skills help my workflow. I know that I 
should commit regularly and that commit messages should describe why I made the 
changes instead of just saying what changed

What I keep having trouble with is how to become the kind of person who does those
things instead of being someone who commits so rarely their messages are 
"finished Script A, wrote Script B, got a good start on Script C". Most of the 
Git resources are more helpful at developing technical skills rather than good
version control habits. This isn't to bash those guides; there's nothing wrong
with having a relatively narrow goal that you do well. 

Also, habits are more personal. The things that have helped me use Git better 
may be useless for you. That said, I wish younger me had something to use as a 
starting point. This is my attempt to write the advice I would have found 
helpful. Hopefully, some of you find it helpful too.

# The key to committing more often is to commit more often 

The first problem I needed to address was that I just wasn't committing often 
enough. It's hard to actually take advantage of Git if going back even one 
commit changes so much that you feel better off just hitting Ctrl-Z a bunch. 
You can't write good messages when a dozen unrelated things have changed.

Fortunately, this had also been the easiest thing to change for me. I often 
went days without committing, so I felt that even shifting to one commit per 
day would be an improvement. I added a reminder for 4pm every workday that just 
said "git commit." 4 was late enough that I would be committing nearly all my 
work the same day I did it but early enough that I didn't feel rushed if I had
a lot I needed to do before leaving.

My plan was to stick to one commit a day until I felt like had built the habit, 
then add a second reminder earlier in the day. Eventually, I'd have enough 
reminders that my commits would usually be a reasonable size. Fortunately, it 
didn't need to have my phone beep at me five times a day. Making commits a daily
habit had the effect of making me more mindful of the fact that I hadn't 
committed well before 4 o'clock. Before long, I was doing multiple commits most
days.

# Explaining why (for broad definitions of "why")
For me, writing better commit messages has been about internalizing that the 
clearest "why I made the commit" may not have to do with the code. I used to 
write messages like "fixed score calculation" and "updated color palette". 
Neither of these are ideal commit messages as they just say things that are
probably obvious from a quick glance at the diff. The problem was I didn't have 
anything that felt like a "proper" commit message, like "old score system lead 
to dividing by strings". The problem wasn't the code per se, just that it 
didn't serve the business needs.

The epiphany came when I realized that "didn't serve the business needs" was a 
perfectly good "why" all by itself, as long as I was clear what those 
shortcomings were. Now I'm often righting commit messages like "SME pointed out
error in the score calculation" and "old color palette was garish".

Admittedly, this is very much a work in progress. Why I know how to write 
better commit messages, I still haven't fully internalized that process. I
still periodically write messages that are too focused on the what or vague as 
to the why, and I've got a while to go before I feel like I have a good sense of
what a good commit message for a blog post looks like.

# Going out on a limb
Even more so than commit messages, my experience with using branches is limited.
This is mostly me theorizing what would be a good way to uses branches more 
effectively. If you have experience in an analytics context (data viz, reports, 
etc.), please feel free to [let me know](https://twitter.com/khailper). I'd 
love to share other people's solutions to this problem.

Looking back at some of my work, I think I should have treated branches like 
a scratch pad. They're have been times when I've experimented with a novel 
graph type or tried to look at the data from another angle, only to create 
something that was confusing or have the data produce no new insights. Since I 
often rewrote larges chunks of the report around these ideas, having to roll
back all the changes has been a regular source of frustration.
